scripts/site/src/app/share/nz-codebox/nz-codebox.component.html
scripts/site/src/app/share/nz-codebox/nz-codebox.component.ts

fix(showcase: codebox): fix show code window back title always show '返回'
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(showcase: codebox): fix show code window back title always show '返回'

---

components/nav-bar/nav-bar.component.html
components/nav-bar/nav-bar.component.spec.ts
components/nav-bar/nav-bar.component.ts
components/nav-bar/nav-bar.module.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(module: nav-bar): add icon string support

---

components/toast/toast.component.ts
components/toast/toast.service.ts

fix(module: Toast): fix tasks can be kicked off via runOutsideAngular and if needed, these tasks can reenter the Angular zone via run
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```

fix(module: Toast):  fix tasks can reenter the Angular zone via run

---

components/date-picker/date-picker.component.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(module: date-picker): fix no locale input will trigger error

---

docs/customize-theme.en-US.md
docs/customize-theme.zh-CN.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(module:showcase): update docs color define

---

components/date-picker/demo/basic.ts
components/locale-provider/demo/basic.ts
components/locale-provider/languages/index.ts
components/locale-provider/locale-provider.spec.ts
schematics/ng-add/schema.json
schematics/ng-add/schema.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: #123 
The Danish locale implementation is complete.
```
[ ] Yes
[X] No
```

fix: Fixes lack of export for Danish locale. Fixes #123.

---

components/popover/doc/index.en-US.md
components/popover/doc/index.zh-CN.md
components/popover/popover-options.provider.ts
components/popover/popover.component.ts
components/popover/popover.directive.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```

feat(module: popover): feat add customClass for customer

---

components/action-sheet/action-sheet-options.provider.ts
components/action-sheet/action-sheet.component.html
components/action-sheet/action-sheet.component.spec.ts
components/action-sheet/action-sheet.component.ts
components/action-sheet/action-sheet.service.ts
components/action-sheet/demo/basic.ts
components/action-sheet/doc/index.zh-CN.md
components/modal/modal.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

perf(module: actionsheet): perf actionsheet with cdk

---

components/input-item/doc/index.en-US.md
components/input-item/doc/index.zh-CN.md
components/input-item/input-item.component.html
components/input-item/input-item.component.spec.ts
components/input-item/input-item.component.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(module: inputitem): fix inputitem extra support template

---

components/textarea-item/demo/basic.ts
components/textarea-item/textarea-item.component.ts

fix(module: textarea-item): fix autoHeight error. (#501)

fix(module: textarea-item): fix autoHeight error. (#501)

---

components/input-item/input-item.component.html
components/input-item/input-item.component.spec.ts
components/input-item/input-item.component.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

feat(module: input-item): fix input-item bug

---

components/accordion/accordion.component.ts
components/accordion/demo/accordion.ts
components/accordion/demo/basic.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(module: accordion): fix accordion not automatic expand bug

---

components/picker/picker.directive.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
fix #336

fix(module: picker): fix select bug when data is a function

---

components/date-picker/date-picker.component.spec.ts

```
[ ] Bugfix
[ ] Feature
```
在`datepicker`的一个测试用例中, 写死了年份为2019年, 现在是2020年了, 会导致这个单测必定失败.
```
[ ] Yes
[x] No
```

fix(module: datepicker): fix unit test failures

---

components/input-item/input-item.component.html
components/input-item/input-item.component.spec.ts
components/input-item/input-item.component.ts
components/input-item/input-item.definitions.ts

close #637 
```
[x] Bugfix
[ ] Feature
```
Issue Number: #637 
en: Under `'text'` type, the cursor position never jump to the right when you modify the value.
cn: 当type为`'text'`时, 修改值时不会再每次都更改光标至最右侧.
```
[ ] Yes
[x] No
```

fix(module: input-item): input cursor always turn to end position

---

components/picker-view/picker-view.component.spec.ts
components/picker-view/picker-view.component.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(module: date-picker-view): add async data input support

---

components/input-item/doc/index.en-US.md
components/input-item/doc/index.zh-CN.md
components/input-item/input-item.component.ts

close #732 
```
[ ] Bugfix
[x] Feature
```
Issue Number: #731 
当[compositionFilter]为true时, 在移动端输入内容, 如中文等需要预览状态的语言, 在完成输入前是不会触发ngModelChange的, 也就是无法更改值. 
当[compositionFilter]为false时, 即便在预览模式下也会修改值.
```
[ ] Yes
[x] No
```

feat: add [compositionFilter] to InputItem

---

components/radio/style/addon.less
components/radio/style/index.less

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(module: radio): fix listitem can't click when not using list wraper

---

components/modal/doc/index.en-US.md

```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
The markdown documentation for the modal component has a broken table and missing/inconsistent backticks.
The markdown has been corrected and unified with the style present in the rest of the document.
```
[ ] Yes
[X] No
```

docs(module: modal): fix formatting and inconsistent backticks

---

components/stepper/demo/basic.ts
components/stepper/stepper.component.html
components/stepper/stepper.component.spec.ts
components/stepper/stepper.component.ts

```
[x] Bugfix
[ ] Feature
```
手动输入除数字之外的字符，显示值会变为NaN
Issue Number: 787、771
1、输入框增加只能输入数字的限制
2、输入框增加小数和负数的输入判断
3、输入框增加 blur 时，对输入值进行有效判断并回填
4、增加相应测试用例
5、增加 demo 示例
```
[ ] Yes
[x] No
```

feat(module: stepper): 修复输入框输入显示问题

---

.travis.yml
components/modal/demo/alert.ts
components/modal/demo/basic.ts
components/modal/demo/operation.ts
components/modal/doc/index.en-US.md
components/modal/doc/index.zh-CN.md
components/modal/modal-options.provider.ts
components/modal/modal.component.spec.ts
components/modal/modal.module.ts
components/modal/modal.service.ts
components/modal/public-api.ts

```
[ ] Bugfix
[x] Feature
```
Modal.operation 不支持点击蒙版关闭弹窗
Issue Number: #799 
Modal.operation 支持点击蒙版关闭弹窗
```
[ ] Yes
[x] No
```

feat(module: modal): Modal.operation support maskClosable params

---

components/calendar/datepicker/datepicker.base.component.ts
package.json

```
[x] Bugfix
[ ] Feature
```
2nd of April is displayed twice when AEDT timezone is used. Some special dates are not 24 hours a day，so currentDay calculation error in the `datepicker.base.component.ts` file on lie 117.
Issue Number: #866 
Use `new Date()` to get the next day.
```
[ ] Yes
[x] No
```

fix(module: calendar): fix calendar date bug

---

components/calendar/locale/en_US.ts
components/locale-provider/locale/calendar/en_US.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #880 
The typo is fixed from "Fir" to "Fri".
```
[ ] Yes
[x] No
```
fixes #880

fix(module: calendar): fix typo in calendar english day names
