- schematics/ng-add/index.ts
- schematics/utils/ast.ts
- schematics/utils/html.ts
- schematics/utils/project-main-file.ts
- schematics/utils/project-targets.ts
- schematics/utils/testing.ts
- site_scripts/template/code.template.html
- site_scripts/utils/generate-code.js
```
[ ] Bugfix
[ ] Feature
```
`ng-add` notwork when Angular-CLI  is 6.2.x
1. Compatibility with Angular CLI 6.2.x
2. Add copy `ng g [schematics_name]` command button in the docs site
```
[ ] Yes
[x] No
```
> build:(schematics): compatibility with Angular CLI 6.2

- components/badge/badge.component.ts
- components/badge/demo/basic.ts
- components/input-item/input-item.component.ts
- components/textarea-item/textarea-item.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(components):remove classname

- components/activity-indicator/activity-indicator.component.ts
- components/core/directive/touch-feedback.directive.ts
- components/core/util/position.ts
- components/flex/flex.component.ts
- components/grid/grid.component.ts
- components/input-item/custom-input/custom-input.component.ts
- components/input-item/custom-input/custom-input.service.ts
- components/input-item/custom-keyboard/custom-keyboard.component.ts
- components/modal/modal.component.ts
- components/popover/doc/index.en-US.md
- components/popover/doc/index.zh-CN.md
- components/popover/popover-item/popover-item.component.ts
- components/popover/popover.component.spec.ts
- components/popover/popover.component.ts
- components/popover/popover.directive.ts
- components/popover/popover.module.ts
- components/range/range.component.spec.ts
- components/slider/slider-marks/slider-marks.component.ts
- components/slider/slider-steps/slider-steps.component.ts
- components/stepper/stepper.component.ts
- components/swipe-action/swipe-action.component.html
- components/swipe-action/swipe-action.component.ts
- package.json
```
[ ] Bugfix
[ ] Feature
```
remove third lib
```
[ ] Yes
[ ] No
```
> Guoyq feature branch

- components/input-item/custom-input/custom-input.component.ts
- components/input-item/custom-input/custom-input.service.ts
- components/input-item/custom-keyboard/custom-keyboard.component.html
- components/slider/slider-marks/slider-marks.component.ts
- components/slider/slider-steps/slider-steps.component.ts
```
[x ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(component):input-item and slider rm classname;

- components/menu/sub-menu/sub-menu.component.ts
- components/tag/tag.component.ts
feat(module:tag):remove classname
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:menu):remove classname and providers

- components/modal/modal.component.spec.ts
feat(module: modal): add modal test
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module: modal): add modal test

- components/input-item/input-item.component.ts
- components/list/demo/form.ts
- components/list/list-item/list-item.component.ts
- package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: list-item): remove classname

- components/input-item/custom-keyboard/custom-keyboard.component.html
- components/input-item/custom-keyboard/custom-keyboard.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: input-item): fixed custom-keyboard hide

- CHANGELOG.md
- components/package.json
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.9.4): release 0.9.4

- package.json
fix(module: package.json): delete not use version key
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: package.json): delete not use version key

- components/popover/popover.directive.ts
- package.json
- scripts/git/commit-message.json
- scripts/git/commit-msg.js
- scripts/git/validate-commit-message.js
fix(module:popover): add provider for PopoverOptions
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:popover): add provider for PopoverOptions

- components/calendar/datepicker/datepicker.component.html
- components/pull-to-refresh/style/addon.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
>  feat(module: calendar): optimize scroll smooth

- components/textarea-item/textarea-item.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:textarea): fix textarea test case error

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> fix(module:codebox): fix StackBlitz with dynamic components

- package.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(package.json): change run start way

- components/tabs/tabs.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: tabs): disable useOnPan when swipeable is false

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.9.5): release 0.9.5

- package.json
- [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build(packaging): change the way to build

- components/components.less
- components/icon/icon.component.ts
- components/icon/style/addon.less
- components/icon/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: icon): fix icon line-height(#46)

- components/textarea-item/textarea-item.component.spec.ts
- components/textarea-item/textarea-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: textarea): fixed textarea-item test case error

- docs/changelog.en-US.md
- docs/contributing.en-US.md
- docs/customize-theme.en-US.md
- docs/getting-started.en-US.md
- docs/introduce.en-US.md
- docs/running-in-ionic.en-US.md
- docs/schematics.en-US.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(showcase): fix grammer error in English Website

- README.md
- scripts/site/_site/src/app/app.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(showcase): add explanation on footer resources

- components/carousel/carousel.component.ts
…ered
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: carousel): add stopPropagation when touch action is triggered

- scripts/site/template/demo-component.template.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(showcase):fix demo preview style

- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(showcase):replace ionic guide link

- components/carousel/carousel.component.spec.ts
- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: carousel): fix carouselslide no width when vertical:false

- scripts/schematics/set-theme.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(packaging):fix the file path to generate theme.less

- components/image-picker/demo/accept.ts
- components/image-picker/demo/basic.ts
- components/image-picker/image-picker.component.html
- components/image-picker/image-picker.component.spec.ts
- components/image-picker/image-picker.component.ts
test(module:image-picker):add missing tests
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test(module:image-picker):add missing tests

- README-zh_CN.md
- docs/introduce.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(showcase): replace dingtalk qrcode

- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(showcase):more description for add styles

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.9.6): release 0.9.6

- components/button/button.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module: button): refactor touch events

- components/action-sheet/action-sheet.component.spec.ts
- components/button/button.component.ts
- components/menu/menu.component.spec.ts
- components/modal/modal.component.spec.ts
- components/pagination/pagination.component.spec.ts
- components/toast/toast.component.spec.ts
fix(module: Toast): fix tasks can be kicked off via runOutsideAngular and if needed, these tasks can reenter the Angular zone via run
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module: button): refactor events

- components/ng-zorro-antd-mobile.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: LocaleProvider): export LOCAL_PROVIDER_TOKEN

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.html
- scripts/site/_site/src/style/demo.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(showcase): change expand icon

- components/action-sheet/action-sheet.component.html
- components/action-sheet/action-sheet.service.ts
…ick event
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> fix(module: action-sheet): fix click item will response background click event

- components/action-sheet/action-sheet.component.html
- components/action-sheet/action-sheet.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: action-sheet): fix click item without event

- components/input-item/custom-input/custom-input.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: input-item): fix set value by ngzone.run

- components/checkbox/checkbox.component.ts
- components/date-picker/date-picker.component.ts
- components/radio/radio.component.ts
- components/tabs/tab-pane.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tabs): fix tabs display error in macos safari

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.9.7): release 0.9.7

- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(changelog): add bugfix title in 0.9.7

- CHANGELOG.md
- components/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.9.8): release 0.9.8

- package.json
- scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(packaging): add publish scripts

- components/core/core.module.ts
- components/picker/picker.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: picker): import OverlayModule

- components/calendar/locale/da_DK.ts
- components/date-picker-view/locale/da_DK.ts
- components/date-picker/locale/da_DK.ts
- components/input-item/locale/da_DK.ts
- components/locale-provider/languages/da_DK.ts
- components/menu/locale/da_DK.ts
- components/pagination/locale/da_DK.ts
- components/picker/locale/da_DK.ts
- components/pull-to-refresh/locale/da_DK.ts
- components/search-bar/locale/da_DK.ts
- package-lock.json
```
[ ] Bugfix
[X] Feature
```
Issue Number: #114
Danish locale has been added.
```
[ ] Yes
[X] No
```
> feat: Adds danish locale. Fixes #114

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Publish 0.9.9

- components/checkbox/checkbox.component.html
- components/radio/radio.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: checkbox&radio): fix output status error

- components/badge/badge.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: badge): add span to badge text

- components/popover/popover.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: popover): fix visible input not use without init

- components/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
>  build(packaging): modify package.json for generate changelog

- components/calendar/calendar.module.ts
- components/ng-zorro-antd-mobile.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: calendar): export calendar module

- components/tab-bar/tab-bar.module.ts
- components/tabs/tabs.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: TabBar): TabsModule import is no needed

- components/pagination/pagination.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:pagination):import LocaleProviderModule

- components/menu/menu.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:menu):import LocaleProviderModule

- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build(module:packaging): change target browsers for autoprefixer

- components/package.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build(module:packaging): autoprefixer only supports ios >=7 & android >=4.4

- components/picker-view/picker-view.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module:PickerView): import PickerModule and  LocaleProviderModule

- components/accordion/accordion.component.ts
- package.json
- scripts/site/_site/src/app/kitchen-sink/kitchen-sink.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build(module:packaging): remove rxjs-compat

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/publish/publish.js
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.9.10): release 0.9.10

- components/style/index.less
- components/style/v2-compatible-reset.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style(module:components):reset basic style

- components/nav-bar/nav-bar.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:nav-bar): change Hostbinding with public define.

- components/accordion/accordion-group/accordion-group.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module:accordion):  change Hostbinding with public define.

- components/switch/demo/basic.ts
- components/switch/doc/index.en-US.md
- components/switch/doc/index.zh-CN.md
- components/switch/switch.component.spec.ts
- components/switch/switch.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module: switch): feat ngModel support

- components/input-item/custom-input/custom-input.component.html
- components/input-item/custom-input/custom-input.component.ts
- components/input-item/input-item.component.html
- components/input-item/input-item.component.spec.ts
- components/input-item/input-item.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: inputitem): add fontColor input

- components/button/button.component.spec.ts
- components/button/button.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:button): fix loading input only work first init.

- components/textarea-item/demo/basic.ts
- components/textarea-item/doc/index.en-US.md
- components/textarea-item/doc/index.zh-CN.md
- components/textarea-item/textarea-item.component.spec.ts
- components/textarea-item/textarea-item.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: textarea-item): add ngModel

- components/calendar/calendar.component.spec.ts
- components/calendar/calendar.component.ts
- components/calendar/demo/basic.ts
- components/calendar/doc/index.en-US.md
- components/calendar/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: calendar): calendar add ngModel

- components/locale-provider/demo/basic.ts
- components/picker/demo/basic.ts
- components/picker/doc/index.en-US.md
- components/picker/doc/index.zh-CN.md
- components/picker/picker-options.provider.ts
- components/picker/picker.component.spec.ts
- components/picker/picker.component.ts
- components/picker/picker.directive.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(module: picker): picker ngModel support

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
Checkbox, Radio, Picker, Switch, InputItem, TextareaItem, Calendar support ngModel now, which will change some of APIs, please check the lastest docs and demos.
> release(0.9.11): release 0.9.11

- components/checkbox/agree-item.component.ts
- components/checkbox/checkbox-item.component.ts
- components/checkbox/checkbox.component.html
- components/checkbox/checkbox.component.ts
- components/radio/radio.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: checkbox): disable checked status while disabled is true

- angular.json
- package.json
- scripts/site/_site/src/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(showcase): fix icon display error

- package.json
- scripts/site/utils/generate-docs.js
- scripts/site/utils/parse-demo-md.js
- scripts/site/utils/parse-doc-md.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(packaging) revert remark package

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
Checkbox, Radio, Picker, Switch, InputItem, TextareaItem, Calendar support ngModel now, which will change some of APIs, please check the lastest docs and demos.
> release(0.10.1): release 0.10.1

- components/picker/picker.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #175 
```
[ ] Yes
[x] No
```
> fix(module: picker): click ok button will throw error when use service

- components/picker-view/demo/basic.ts
- components/picker-view/doc/index.en-US.md
- components/picker-view/picker-view.component.spec.ts
- components/picker-view/picker-view.component.ts
- components/picker-view/picker-view.module.ts
- components/picker/picker.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(module: picker-view): perf docs and demo

- components/core/services/popup.service.ts
- components/modal/demo/alert.ts
- components/modal/demo/basic.ts
- components/modal/demo/prompt.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/modal-options.provider.ts
- components/modal/modal.component.html
- components/modal/modal.component.spec.ts
- components/modal/modal.component.ts
- components/modal/modal.module.ts
- components/modal/modal.service.ts
- components/ng-zorro-antd-mobile.module.ts
- scripts/site/_site/src/app/app.module.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
- scripts/site/_site/src/styles.less
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> refactor(module:Modal): refactor modal base on CDK Overlay

- components/notice-bar/demo/basic.ts
- components/notice-bar/doc/index.en-US.md
- components/notice-bar/doc/index.zh-CN.md
- components/notice-bar/notice-bar.component.html
- components/notice-bar/notice-bar.component.spec.ts
- components/notice-bar/notice-bar.component.ts
- components/notice-bar/notice-bar.module.ts
- components/notice-bar/style/notice-bar.less
- components/notice-bar/util.ts
- components/pull-to-refresh/demo/basic.ts
- components/swipe-action/demo/basic.ts
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
>  refactor(module: NoticeBar): refactor NoticeBar

- components/search-bar/demo/basic.ts
- components/search-bar/doc/index.en-US.md
- components/search-bar/doc/index.zh-CN.md
- components/search-bar/search-bar.component.spec.ts
- components/search-bar/search-bar.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: searchbar): searchbar add ngModel

- components/action-sheet/action-sheet.component.html
- components/action-sheet/action-sheet.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: ActionSheet): fix when no title or message would not show blank on header

- components/checkbox/agree-item.component.ts
- components/checkbox/checkbox-item.component.ts
- components/checkbox/demo/basic.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: checkbox): fix checkbox init status when checked is true

- components/textarea-item/textarea-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: textarea-item): fix textarea value can't be 0 or ''

- components/input-item/input-item.component.spec.ts
- components/input-item/input-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: input-item): fix input value can't be 0 or ''

- components/textarea-item/textarea-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: textarea-item): fix textarea-item value protect

- components/calendar/calendar.component.spec.ts
- components/date-picker-view/date-picker-view.component.spec.ts
- components/date-picker-view/date-picker-view.component.ts
- components/date-picker-view/date-picker-view.module.ts
- components/date-picker-view/demo/basic.ts
- components/date-picker-view/doc/index.en-US.md
- components/date-picker-view/doc/index.zh-CN.md
- components/date-picker/date-picker-options.provider.ts
- components/date-picker/date-picker.component.html
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.directive.ts
- components/date-picker/date-picker.module.ts
- components/date-picker/demo/basic.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
- components/date-picker/index.ts
- components/date-picker/locale/zh_CN.ts
- components/date-picker/public-api.ts
- components/locale-provider/demo/basic.ts
- components/modal/modal.module.ts
- components/style/themes/default.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
>  feat(module: date-picker): feat deal date-picker input error value with toast tips

- components/date-picker-view/date-picker-view.component.spec.ts
- components/date-picker-view/date-picker-view.component.ts
- components/date-picker-view/date-picker-view.module.ts
- components/date-picker-view/demo/basic.ts
- components/date-picker-view/doc/index.en-US.md
- components/date-picker-view/doc/index.zh-CN.md
- components/date-picker/date-picker-options.provider.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.directive.ts
- components/date-picker/date-picker.module.ts
- components/date-picker/demo/basic.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(module: date-picker): feat support date-picker ngModel

- scripts/site/_site/src/app/share/nz-nav-bottom/nz-nav-bottom.component.ts
- scripts/site/_site/src/style/page-nav.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(showcase): feat change icon to nz-icon

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package-lock.json
```
[x] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
DatePicker、PickerView、PullToRefresh、Range、SearchBar、Slider、Stepper support ngModel，
please check docs for details
> release(0.11.0): release 0.11.0

- scripts/site/_site/src/app/share/nz-nav-bottom/nz-nav-bottom.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(showcase): fix website icon show error bug

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: codebox): update zorro mobile version

- components/core/directive/touch-feedback.directive.ts
- components/grid/grid.component.html
…eedback
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module: TouchFeedbackDirective): refactor duplication  TouchFeedback

- components/menu/menu.component.ts
…Check
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module:menu): add locale type to fit fullTemplateTypeCheck

- components/modal/modal.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: modal): fix no actions would work error.

- components/carousel/carousel.component.ts
- components/carousel/demo/basic.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: carousel): fix carousel selectedIndex init work error

- components/pull-to-refresh/pull-to-refresh.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:pulltorefresh): fix when not use ngmodel worked error

- components/action-sheet/action-sheet.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: actionsheet): fix actionsheet not destory unsubscribe for locale

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.directive.ts
- components/date-picker/demo/basic.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: datepicker): feat set disabled work

- components/carousel/carousel.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: carousel): feat when item=1 can not drag

- components/switch/switch.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:switch): feat add  active an inactive class for modify css

- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:date-picker): fix set minDate error

- CHANGELOG.md
- components/package.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.11.3): release 0.11.3

- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: showcase): update style link

- components/search-bar/search-bar.component.html
- components/search-bar/search-bar.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: searchbar): fix ios9 chinese character bug

- components/input-item/input-item.component.html
- components/input-item/input-item.component.spec.ts
- components/input-item/input-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: input-item): fix ios9 chinese character bug

- components/grid/demo/basic.ts
- components/grid/grid.component.html
- components/grid/grid.component.spec.ts
- components/grid/grid.component.ts
- components/grid/grid.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module: grid): support custom icon and local assets

- components/activity-indicator/style/index.less
- components/badge/style/index.less
- components/carousel/style/index.less
- components/checkbox/style/index.less
- components/icon/style/index.less
- components/image-picker/style/addon.less
- components/image-picker/style/index.less
- components/notice-bar/style/index.less
- components/search-bar/style/index.less
- components/stepper/style/index.less
- components/steps/style/index.less
- components/style/mixins/index.less
- components/switch/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module: style): delete mixins/index.less

- components/drawer/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style(module: drawer): fix z-index

- components/date-picker/date-picker.component.ts
…x date
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): fix select interval when set max date

- components/carousel/carousel.component.spec.ts
- components/carousel/carousel.component.ts
- components/carousel/demo/basic-dynamic.ts
- components/carousel/demo/basic.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: carousel): fix set Carousel component selectedIndex invalid.

- components/button/demo/basic.ts
- components/button/style/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module: button): feat add dashed type.

- components/notice-bar/style/notice-bar.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: notice-bar): fix notice-bar-card color

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.11.4): release 0.11.4

- components/swipe-action/demo/basic.ts
- components/swipe-action/doc/index.en-US.md
- components/swipe-action/doc/index.zh-CN.md
- components/swipe-action/swipe-action.component.spec.ts
- components/swipe-action/swipe-action.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: swipe-action): fix autoclose not work bug

- components/stepper/stepper.component.spec.ts
- components/stepper/stepper.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: stepper): fix stepper js float calculation bug

- components/action-sheet/action-sheet.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: actionsheet): fix code title->message error

- components/tab-bar/style/addon.less
- [x ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd-mobile/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(module: tabbar): enlarge tabbartab click zone

- components/date-picker-view/date-picker-view.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: date-picker-view): fix value input not work

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.11.5): release 0.11.5

- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: carousel): fix carousel detect height change need to init carouseItem

- components/action-sheet/action-sheet.service.ts
- components/core/services/popup.service.ts
- components/modal/modal.service.ts
- components/picker/demo/basic.ts
- components/picker/picker.service.ts
…ng error
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: PupupService): fix when using multiple PupupService working error

- components/tabs/tabs.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tabs): disable descendants

- components/accordion/accordion-group/accordion-group.component.html
- components/accordion/accordion-group/accordion-group.component.spec.ts
- components/accordion/accordion-group/accordion-group.component.ts
- components/accordion/accordion.module.ts
- components/accordion/demo/basic.ts
- components/accordion/doc/index.en-US.md
- components/accordion/doc/index.zh-CN.md
…t innerHtml
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: accordion): fix accordion support template and add support innerHtml

- components/textarea-item/doc/index.en-US.md
- components/textarea-item/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: textarea-item): update textarea-item docs

- components/input-item/doc/index.en-US.md
- components/input-item/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: inputitem): update inputitem docs

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/doc/index.en-US.md
- components/date-picker/doc/index.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:date-picker): fix select error when ngmodel set to null

- components/drawer/doc/index.zh-CN.md
- components/drawer/drawer.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: drawer): synchronize code and documentation

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.11.6): release 0.11.6

- components/accordion/demo/basic.ts
- components/grid/demo/basic.ts
- components/grid/grid.component.spec.ts
- scripts/site/_site/src/manifest.json
- [] Tests for the changes have been added (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: assets): fix logo name

- components/grid/grid.component.html
- components/grid/grid.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: (module: grid): fix return contentType error

- components/action-sheet/action-sheet.service.ts
- components/core/services/popup.service.ts
- components/modal/modal.service.ts
- components/picker/picker.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: popupservice): fix popupservice get component name with build prod runtime error

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.11.7): release 0.11.7

- components/tab-bar/demo/basic.ts
- components/tab-bar/tab-bar.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> fix: (module: tabbar): fix tabbar set activeTab not work and add demo

- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: carousel): fix carousel vertical mode error

- components/core/services/popup.service.ts
- components/picker/picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: picker): fix async picker data need to update selected data

- components/modal/modal.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(module: modal): perf modal import CoreModule.

- components/accordion/accordion.component.spec.ts
- components/accordion/accordion.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: accordion): fix accordion support async load accordionPanel

- components/carousel/style/carousel-slide.less
```
[ x] Bugfix
[ ] Feature
```
add 'left:0'
Issue Number: #356 
the carousel dot will center
```
[ ] Yes
[x] No
```
> fix(module: carousel): fix carousel style error

- components/grid/doc/index.en-US.md
- components/grid/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs(module: grid): fix error doc of onClick -> OnClick and add activeStyle

- components/picker/picker.component.html
- components/picker/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:picker): fix picker wrap z-index same as mask

- components/input-item/input-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: inputitem): fix inputitem label css init

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.11.8): release 0.11.8

- components/toast/doc/index.en-US.md
- components/toast/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: Toast): fix error unit of duration

- components/input-item/input-item.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: inputitem): fixed style flash

- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:carousel): fix if carousel Out of sight stop carousel play.

- components/steps/style/addon.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style(module: steps): styles update

- components/date-picker-view/date-picker-view.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: datepickerview): fix days can't select 31

- components/date-picker-view/date-picker-view.component.ts
Reverts NG-ZORRO/ng-zorro-antd-mobile#383
> Revert "fix(module: datepickerview): fix days can't select 31"

- components/calendar/style/addon.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: calendar): fix calendar concat antd mobile css bug

- components/picker/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: picker): fix style error.

- CHANGELOG.md
- components/core/util/icon.ts
- components/package.json
- components/steps/demo/basic.ts
- components/steps/steps.component.spec.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/assets/fonts/Lato/Lato-Regular.svg
- scripts/site/_site/src/assets/fonts/Raleway/Raleway.svg
- scripts/site/_site/src/assets/fonts/iconfont.svg
- scripts/site/_site/src/assets/img/angular.svg
- scripts/site/_site/src/assets/img/logo.svg
- scripts/site/_site/src/assets/img/zorro.svg
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.11.9): release 0.11.9

- components/modal/modal.module.ts
- components/ng-zorro-antd-mobile.module.ts
- components/toast/toast.module.ts
- scripts/site/_site/src/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore(packaging): chore dynamic components export.

- schematics/ng-add/schema.json
- scripts/schematics/template/schema.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: schematics): change $schema url from https to http

- components/grid/demo/basic.ts
- components/grid/doc/index.en-US.md
- components/grid/doc/index.zh-CN.md
- components/grid/grid.component.spec.ts
- components/grid/grid.component.ts
- components/notice-bar/notice-bar.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> fix(module: grid): change API OnClick to onClick

- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- scripts/site/template/doc-component.template.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(module: site): update homepage

- rollup.config.js
- scripts/site/generate-site.js
- scripts/site/utils/generate-demo.js
- scripts/site/utils/generate-iframe-demo.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore(module: scripts): code specification optimization

- components/action-sheet/style/index.less
- components/modal/style/Dialog.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: styles): sync with ant design mobile of react

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> perf(module: code-box): perf code-box open stackblitz.

- components/checkbox/checkbox-item.component.html
- components/checkbox/checkbox-item.component.ts
- components/checkbox/doc/index.en-US.md
- components/checkbox/doc/index.zh-CN.md
- components/radio/doc/index.en-US.md
- components/radio/doc/index.zh-CN.md
- components/radio/radio-item.component.html
- components/radio/radio-item.component.ts
- components/radio/style/addon.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: checkboxitem&radioitem): support wrap API

- components/stepper/stepper.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: stepper): fixed stepper disabled bug

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
* **tabbar:** TabBarItem instead of TabPane&TabBarTab, make it more simple ([#399](https://github.com/NG-ZORRO/ng-zorro-antd-mobile/issues/399)) ([f82ceab](https://github.com/NG-ZORRO/ng-zorro-antd-mobile/commit/f82ceab))
* **grid:** change API OnClick to onClick ([#394](https://github.com/NG-ZORRO/ng-zorro-antd-mobile/issues/394)) …
> release(0.12.0): release 0.12.0

- components/carousel/carousel.component.spec.ts
- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:carousel): fix adaptive when switching screens

- scripts/site/_site/src/app/app.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: mobile site): correct component name in mobile site

- components/checkbox/checkbox.component.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> test(module: checkbox): add missing checkboxItem unit test

- components/action-sheet/demo/basic.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: action-sheet): fix error doc of providers: [Toast] -> providers: [Toast, ActionSheet]

- components/input-item/demo/basic.ts
- components/modal/demo/alert.ts
- components/modal/demo/basic.ts
- components/modal/demo/operation.ts
- components/modal/demo/prompt.ts
- [z] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd-mobile/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[z] Application (the showcase website) / infrastructure changes
```
```
[ ] Yes
[x] No
```
> fix(module: modal&input-item): add essential providers to make demo work

- components/tab-bar/tab-bar.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #418 
```
[ ] Yes
[x] No
```
> fix(module: tabbar):fix tintColor invalid(#418)

- components/core/types/common-wrap.ts
- components/stepper/stepper.component.spec.ts
- components/stepper/stepper.component.ts
```
[x] Bugfix
[ ] Feature
```
#402 
Issue Number: 402
```
[ ] Yes
[x] No
```
> fix(module:stepper):fix disabled invalid(#402)

- components/swipe-action/demo/basic.ts
- components/swipe-action/doc/index.en-US.md
- components/swipe-action/doc/index.zh-CN.md
- components/swipe-action/swipe-action.component.html
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: swipe-action): add className api

- components/calendar/calendar.component.ts
- components/calendar/util/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: calendar): fix calendar timepicker display title error bug

- components/action-sheet/doc/index.en-US.md
- components/action-sheet/doc/index.zh-CN.md
- components/calendar/calendar.component.spec.ts
- components/date-picker-view/date-picker-view.component.spec.ts
- components/date-picker-view/date-picker-view.module.ts
- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.module.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/toast/doc/index.en-US.md
- components/toast/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module: toast&modal&action-sheet): del usage of entryComponents

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.12.1): release 0.12.1

- components/action-sheet/action-sheet.module.ts
- components/core/services/popup.service.ts
- components/modal/modal.module.ts
- components/picker/picker.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: popupservice): set popupservice providers in referenced components.

- components/toast/demo/basic.ts
- components/toast/doc/index.en-US.md
- components/toast/doc/index.zh-CN.md
- components/toast/style/addon.less
- components/toast/style/index.less
- components/toast/toast-options.provider.ts
- components/toast/toast.component.spec.ts
- components/toast/toast.component.ts
- components/toast/toast.service.ts
- tslint.json
```
[] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:toast): support position top and bottom

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.12.2): release 0.12.2

- components/tab-bar/tab-bar.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
add unit test
```
[ ] Yes
[x] No
```
> test(module: tabbar): add missing tabbar unit test

- components/date-picker/date-picker.component.ts
- components/date-picker/demo/basic.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: datepicker): fix new Date init in safari would be invlid date.

- components/date-picker/demo/basic.md
- components/date-picker/demo/basic.ts
- components/date-picker/demo/date.md
- components/date-picker/demo/date.ts
- components/date-picker/demo/disable.md
- components/date-picker/demo/disable.ts
- components/date-picker/demo/max-date.md
- components/date-picker/demo/max-date.ts
- components/date-picker/demo/min-date.md
- components/date-picker/demo/min-date.ts
- components/date-picker/demo/month.md
- components/date-picker/demo/month.ts
- components/date-picker/demo/time.md
- components/date-picker/demo/time.ts
- components/date-picker/demo/utc-time.md
- components/date-picker/demo/utc-time.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(showcase): refactor date-picker showcase of website.

- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: date-picker): fix caculate time error.

- components/picker/picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:picker): fix return result error

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: stackblitz): set right version for @angular/compiler

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(0.12.3): release 0.12.3

- components/drawer/drawer.component.spec.ts
- components/drawer/drawer.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module: drawer): delete useless code

- components/menu/sub-menu/sub-menu.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(module: menu): refactor code

- components/swipe-action/swipe-action.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(module: swipe-action): add missing test

- components/input-item/input-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: input-item): fix value bug when clear

- components/calendar/calendar.component.spec.ts
- components/calendar/calendar.component.ts
- components/calendar/datepicker/datepicker.component.ts
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
> feat(module: calendar): update testing coverage

- components/carousel/carousel-slide/carousel-slide.component.ts
- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: carousel): fix vertical mode width error.

- components/date-picker/date-picker.component.spec.ts
- components/date-picker/date-picker.component.ts
- components/date-picker/date-picker.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: datepicker): add minuteStep support

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package-lock.json
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(0.12.4): release 0.12.4

- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: carousel): fix carousel has one item width error.

- README-zh_CN.md
- README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: README): add CodeFactor&Twitter

- components/calendar/calendar.component.ts
- scripts/site/_site/src/app/app.component.ts
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/ng-zorro/ng-zorro-antd-mobile/issues?category=Maintainability).
> Apply fixes from CodeFactor

- components/picker/picker.component.spec.ts
- components/picker/picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:picker): fix okText dismissText api

- components/radio/radio-item.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: radio): delete duplicated API

- components/carousel/carousel.component.spec.ts
- components/carousel/carousel.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(module: carousel): update testing coverage

- components/search-bar/doc/index.en-US.md
- components/search-bar/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: searchbar): update documents

- components/input-item/demo/basic.ts
- components/input-item/doc/index.en-US.md
- components/input-item/doc/index.zh-CN.md
- components/input-item/input-item.component.html
- components/input-item/input-item.component.spec.ts
- components/input-item/input-item.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[] No
```
> feat(module: input-item): add label content api 

- components/result/demo/basic.ts
- components/result/result.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(module: result): delete basic test & modify spec test

- components/result/result.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(module: result): update code coverage

- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(packaging): move pre-commit hook into husky

- components/action-sheet/action-sheet-options.provider.ts
- components/action-sheet/action-sheet-ref.class.ts
- components/action-sheet/action-sheet.component.spec.ts
- components/action-sheet/action-sheet.component.ts
- components/action-sheet/action-sheet.service.ts
- components/action-sheet/demo/basic.ts
- components/action-sheet/doc/index.en-US.md
- components/action-sheet/doc/index.zh-CN.md
- components/action-sheet/public-api.ts
- components/core/services/popup.service.ts
- components/modal/demo/alert.ts
- components/modal/demo/operation.ts
- components/modal/demo/prompt.ts
- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
- components/modal/modal-options.provider.ts
- components/modal/modal-ref.class.ts
- components/modal/modal.component.spec.ts
- components/modal/modal.component.ts
- components/modal/modal.service.ts
- components/modal/public-api.ts
- components/picker/demo/basic.ts
- components/picker/doc/index.en-US.md
- components/picker/doc/index.zh-CN.md
- components/picker/picker-ref.class.ts
- components/picker/picker.component.spec.ts
- components/picker/picker.component.ts
- components/picker/picker.service.ts
- components/picker/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Popup refactor

- components/action-sheet/demo/basic.ts
- components/date-picker/date-picker.component.ts
- components/input-item/demo/basic.ts
- components/modal/demo/alert.ts
- components/modal/demo/prompt.ts
- components/toast/demo/basic.ts
- components/toast/doc/index.en-US.md
- components/toast/doc/index.zh-CN.md
- components/toast/toast.component.spec.ts
- components/toast/toast.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(module: toast): toast refactor

- components/modal/modal-options.provider.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: modal): fix visable init value as false

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.html
- scripts/site/_site/src/app/app.component.ts
```
[x] Bugfix
[x] Feature
[x] CI related changes
```
```
[x] Yes
[ ] No
```
toast, modal, picker, and action-sheet will be initiated differently.
input-item will have a new API called content instead of ng-content.
> release(1.0.0-beta.0): release 1.0.0-beta.0

- components/modal/modal.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: modal): fix func call error.

- components/stepper/stepper.component.html
- components/stepper/stepper.component.spec.ts
- components/stepper/stepper.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: stepper): fix button status when the user enters

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/publish/publish.js
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.0-beta.1): release 1.0.0-beta.1

- package.json
- scripts/site/_site/src/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: website): fix website run error

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: codebox): fix rawCode convert bug

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style(module: codebox): refact code style in stackblitz

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: codebox): fix copy code error

- scripts/site/_site/src/app/app.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: website): fix version map

- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(module: package): update package script

- components/list/list.component.ts
- package.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: List): fix typescript build error

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/publish/publish.js
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.0-beta.2): release 1.0.0-beta.2

- components/swipe-action/swipe-action.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: swipe-action): fix swipe-action not work in ionic bug

- components/textarea-item/textarea-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix: fixed textarea-item autoheight issues

- components/pull-to-refresh/demo/basic.ts
- components/pull-to-refresh/doc/index.zh-CN.md
- components/pull-to-refresh/pull-to-refresh.component.html
- components/pull-to-refresh/pull-to-refresh.component.ts
- components/pull-to-refresh/pull-to-refresh.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: pull-to-refresh): fix pull-to-refresh not work bug & code refactor

- components/steps/steps.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix: step status is disabled

- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: carousel): fix carousel style int other content error

- CHANGELOG.md
- components/accordion/accordion.component.ts
- components/accordion/demo/basic.ts
- components/package.json
- components/pull-to-refresh/pull-to-refresh.component.html
- components/pull-to-refresh/pull-to-refresh.component.ts
- components/steps/steps.component.ts
- components/textarea-item/textarea-item.component.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.0-rc.0): release 1.0.0-rc.0

- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
fix #579
> fix(module: date-picker): fix NAN bug when fast scroll

- CHANGELOG.md
- components/date-picker/date-picker.component.ts
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.0): release 1.0.0

- components/picker/picker.component.spec.ts
- components/picker/picker.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: picker): remove lodash isEqual reference

- CHANGELOG.md
- components/package.json
- components/picker/picker.component.spec.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.1): release 1.0.1

- components/checkbox/checkbox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: checkbox): fix checked initial status when disabled is true

- components/list/demo/form.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: list): fix inputitem demo

- components/list/list.component.ts
- components/range/range.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: list&range): delete console.log

- components/pagination/pagination.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: pagination): fix set locale not work bug

- components/accordion/accordion-group/accordion-group.component.ts
- components/accordion/accordion.component.spec.ts
…quick click
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: accordion): fix accordion expand and collapse error when quick click

- components/date-picker/locale/zh_CN.ts
- [] Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: datepicker): fix chinese prompt

- components/carousel/carousel.component.spec.ts
- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: carousel): fix carousel slide error when resize

- components/tabs/style/addon.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tabs): make popup components working right in Tabs&TabBar

- components/calendar/calendar.component.spec.ts
- components/calendar/single-month/single-month.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: calendar): should get extra cell class name from cell

- components/steps/steps.component.spec.ts
- components/steps/steps.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: steps): fix step import async

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.2): release 1.0.2

- components/drawer/drawer.component.html
- components/drawer/style/addon.less
- docs/contributing.zh-CN.md
close #623 
```
[x] Bugfix
[ ] Feature
```
Issue Number: #623 
```
[ ] Yes
[x] No
```
> bugfix: drawer can not cover elements under background

- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #626 
```
[ ] Yes
[x] No
```
> fix(module: date-picker): cannot choose maximum  and minimum time

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.3): release 1.0.3

- components/modal/doc/index.en-US.md
- components/modal/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: modal): fix modal docs error

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.4): release 1.0.4

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: changelog): delete error changlog

- components/steps/demo/basic.ts
- components/steps/step/step.component.html
- components/steps/step/step.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: steps): step title&description support templateRef input

- CHANGELOG.md
- components/package.json
- components/steps/demo/basic.ts
- components/steps/doc/index.en-US.md
- components/steps/doc/index.zh-CN.md
- components/steps/step/step.component.ts
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.5): release 1.0.5

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> release(2.0.0): release 2.0.0

- package.json
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feature(module: stackblitz): update stackblitx dependecies

- CHANGELOG.md
- components/locale-provider/locale-provider.module.ts
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(2.0.1): release 2.0.1

- components/accordion/accordion-group/accordion-group.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: accordion): add nzm-selector

- package.json
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: stackblitz): update stackblitz @angular/cdk dependency

- components/tabs/default-tab-bar.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: tabs): fix tabs calculate lose precision

- components/action-sheet/action-sheet.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: action-sheet): import TouchFeedbackDirective

- components/picker/picker.directive.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: picker): fix binding assignment

- components/textarea-item/textarea-item.component.spec.ts
- components/textarea-item/textarea-item.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: textarea-item): fix count not work after ngModel write value

- components/date-picker/date-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: date-picker): fix mindate change month error

- components/menu/doc/index.en-US.md
- components/menu/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update error MD grammar

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix tooltip title error

- components/accordion/accordion-group/accordion-group.component.html
- components/accordion/accordion-group/accordion-group.component.ts
- components/accordion/accordion.module.ts
- components/accordion/demo/basic.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> fix(module: accordion): no longer support innerHtml

- components/input-item/input-item.component.spec.ts
- components/input-item/input-item.component.ts
- components/textarea-item/textarea-item.component.spec.ts
- components/textarea-item/textarea-item.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: input-item and textarea-item) add setdisabled

- components/pull-to-refresh/pull-to-refresh.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:pulltorefresh): fix element height

- components/grid/grid.component.spec.ts
- components/grid/grid.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: grid): fix columnNum and carouselMaxRow not work

- components/date-picker-view/date-picker-view.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: datepickerview): fix datePickerOptions singleton pattern

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(1.0.6): release 1.0.6

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(2.0.2): release 2.0.2

- components/image-picker/image-picker.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: image-picker): fix rotate not work

- components/modal/modal.component.ts
```
[x] Bugfix
[ ] Feature
```
#720 
```
[ ] Yes
[x] No
```
> fix(module: modal): fix `maskClosable` not work

- components/drawer/drawer.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: drawer): fix drawer flash back with tabs

- scripts/site/utils/generate-docs.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(module: website): del undefined msg in website

- docs/customize-theme.en-US.md
- docs/customize-theme.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix customize theme iconfont import error

- components/input-item/doc/index.en-US.md
- components/input-item/doc/index.zh-CN.md
- components/input-item/input-item.component.ts
> feat: add [compositionFilter] to InputItem(cherry-pick)

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(2.0.7): release 2.0.7

- scripts/site/template/title.template.html
修复了官网二维码介绍的方向错误
```
[x] Bugfix
[ ] Feature
```
官网二维码的方向错位了, 之前是向上的popover, 会被导航栏遮挡.
popover向下, 不会遮挡, 与react那边保持一致. 
```
[ ] Yes
[x] No
```
> fix: direction error of QRCode

- components/input-item/doc/index.en-US.md
- components/input-item/doc/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix error describe

- components/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: bump components to v10

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> release(3.0.2): release 3.0.2

- components/tab-bar/tab-bar-item.component.ts
close #750 
```
[x] Bugfix
[ ] Feature
```
Issue Number: 750
```
[ ] Yes
[x] No
```
> fix(module: tabbar): typescript error

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(3.0.3): release 3.0.3

- components/search-bar/search-bar.component.html
- components/search-bar/search-bar.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #759 
```
[ ] Yes
[x] No
```
> fix(module: search-bar) fix IME input

- components/steps/demo/basic.ts
- components/steps/step/step.component.ts
- components/steps/steps.component.spec.ts
- components/steps/steps.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: steps): add current support

- components/carousel/carousel.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: carousel): fix when resize active slider error show

- components/pagination/pagination.component.html
- components/pagination/pagination.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module: pagination): add disabled support

- components/range/range.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: range): fix unit test failures

- .github/workflows/codeql-analysis.yml
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: security
```
```
[ ] Yes
[x] No
```
> feat(module: security):  add codeql-analysis

- README-zh_CN.md
- README.md
- docs/introduce.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: website): fix dingtalk QR Code; fix Angular support version;

- scripts/site/generateColorLess.js
```
[ ] Bugfix
[ ] Feature
```
`npm run start` 控制台报错：
`error TypeError: Cannot read property 'slice' of undefined`
报错信息小时
```
[ ] Yes
[x] No
```
> feat(module:core): 修复项目启动报错

- components/input-item/custom-input/custom-input.component.ts
- components/input-item/demo/basic.ts
```
[x] Bugfix
[ ] Feature
```
InputItem type类型设置为money情况下，没有验证数字格式。
Issue Number: 618
InputItem type类型设置为money情况下，只允许输入一个小数点且不能是首位。
```
[ ] Yes
[x] No
```
> fix(module: input-item): fix input decimal point problem

- components/toast/doc/index.en-US.md
- components/toast/doc/index.zh-CN.md
- components/toast/toast.component.spec.ts
- components/toast/toast.service.ts
```
[x] Bugfix
[ ] Feature
```
在生命周期ngOnInit里面调Toast轻提示会报错ERROR Error: ApplicationRef.tick is called recursively
Issue Number: 640
不再报错
```
[ ] Yes
[x] No
```
> fix(module: toast): called in ngOnInit will report an error

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
Angular 12 Support
> release(5.0.0): release 5.0.0

- components/badge/style/index.less
- components/search-bar/style/index.less
- components/style/index.less
```
[x] Bugfix
[ ] Feature
```
1、searchBar 在 ios15 下展示异常。
2、ios 下的样式不支持除法计算，导致 searchBar、badge 组件展示异常。
1、增加 webkit 样式兼容后，展示正常。
2、增加 calc 兼容后，展示正常。
```
[ ] Yes
[x] No
```
> Fix ios style exception

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> release(5.0.1): release 5.0.1

- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.html
```
[ ] Bugfix
[ ] Feature
```
官网 demo 代码弹窗不显示代码内容。
弹窗显示代码内容。
```
[ ] Yes
[x] No
```
> fix(showcase): fix the problem that the pop-up code is not displayed

- components/carousel/carousel.component.ts
```
[ ] Bugfix
[x] Feature
```
https://github.com/NG-ZORRO/ng-zorro-antd-mobile/issues/807
#807
prevent android browser default scroll
在安卓浏览器中阻止走马灯区域默认滚动触发
```
[ ] Yes
[x] No
```
> feat(module:carousel):prevent android browser default scroll

- package.json
- scripts/publish/publish.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: 暂时屏蔽colors异常导致无法发布问题
```
参考 https://github.com/Marak/colors.js/issues/289
```
[ ] Yes
[x] No
```
> feat(publish exception): shield colors depend

- CHANGELOG.md
- components/package.json
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- scripts/site/_site/src/app/app.component.ts
- scripts/site/_site/src/app/share/nz-codebox/nz-codebox.component.ts
```
[x] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> release(6.0.0): release 6.0.0

- components/stepper/stepper.component.html
- components/stepper/stepper.component.spec.ts
- components/stepper/stepper.component.ts
- components/tsconfig.lib.prod.json
```
[ ] Bugfix
[x] Feature
```
Issue Number: #824 
by default,stepper now bring up numeric keypad
```
[ ] Yes
[x] No
```
> feat(module: stepper): bring up numeric keypad

- angular.json
- components/calendar/calendar.component.spec.ts
- components/tabs/tabs.component.spec.ts
- package.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test: 修复 calendar 组件和 tabs 组件单测失败

- components/picker/picker.component.ts
pickerview下拉选择时，选项一半（50%）已经进入待选框，但不会选种，超过100%未到150%时会选种第二个。
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module: picker): fix drop down selection (#805)

- components/date-picker/date-picker.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(module:date-picker): 修复设置最小值的情况下，月份变更后，日期筛选不完整的bug

- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(changelog): fix language bug;

- scripts/site/_site/src/app/app.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(module: website): update site cdn  version

- components/popover/style/index.less
```
[x] Bugfix
[ ] Feature
```
User Agent Stylesheet causes the Popover component to display abnormally。
```
[ ] Yes
[x] No
```
> fix(module: popover): remove [popover] user agent styles

- .gitignore
- abc.json
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
> feat: add .gitkeep to .gitignore&add abc.json
